# MIE1624 Introduction to Data Science and Analytics

# Assignment 3: Sentiment Analysis

### Name: Jiani Jia

### ID: 1002226245

In [125]:
import pandas as pd
import re
import unicodedata

## 1 Data Cleaning

In [126]:
sentiment_analysis_df = pd.read_csv('sentiment_analysis.csv')
sentiment_analysis_df

                  ID                                               text  label
0       7.680980e+17  Josh Jenkins is looking forward to TAB Breeder...      1
1       7.680980e+17  RT @MianUsmanJaved: Congratulations Pakistan o...      1
2       7.680980e+17  RT @PEPalerts: This September, @YESmag is taki...      1
3       7.680980e+17  RT @david_gaibis: Newly painted walls, thanks ...      1
4       7.680980e+17  RT @CedricFeschotte: Excited to announce: as o...      1
...              ...                                                ...    ...
550386  8.046170e+17  @goddesses_o I can't stop watching her...mm. M...      0
550387  8.046180e+17  Poor old Tom Odell doesn't look like he would ...      0
550388  8.046180e+17  #antsmasher I smashed  7 ants in this awesome ...      1
550389  8.046180e+17  @LizHudston @KymWyllie @Evasmiless @meanBok @l...      1
550390  8.046190e+17  Bixbeat Mixtape Vol.2 is here with great artis...      1

[550391 rows x 3 columns]

In [127]:
US_Elections_df = pd.read_csv('US_Elections_2020.csv')
US_Elections_df

,text,sentiment,negative_reason
0,"b'@robreiner so afraid of Nov, Dec, and Jan! E...",0,covid19
1,"b""RT @SueC00K: Lord Sumption launches Recovery...",0,others
2,b'RT @WalidPhares: Uber Timing: after #Biden a...,0,covid19
3,b'Every 107 seconds an American is dying from ...,1,NaN
4,b'RT @thewebbix: The #Democrats embrace #Diver...,1,NaN
...,...,...,...
2547,"b'RT @BoycottUtah: It is Friday, October 30, 2...",1,NaN
2548,b'@nowthisnews Delivered today in Montgomery C...,1,NaN
2549,b'@DonaldJTrumpJr DUHnnie Jr. lied on Fox when...,0,covid19
2550,b'RT @Pale_Ranger: Any ideas why @JoeBiden is ...,0,covid19
2551,"b'RT @cazaresforcoc: game time, keep up our mo...",1,NaN

### 1.1 Remove all html tags and attributes (i.e., /<[^>]+>/)

In [128]:
sentiment_text = sentiment_analysis_df['text']
US_Elections_text = US_Elections_df ['text']

In [129]:
# Using a regex, compile the regex pattern and match them into original text
def remove_html(text):
    cleanr = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
    cleantext = re.sub(cleanr, '', text)
    return cleantext

In [130]:
sentiment_analysis_df['text'] = sentiment_text.apply(remove_html)
sentiment_analysis_df

                  ID                                               text  label
0       7.680980e+17  Josh Jenkins is looking forward to TAB Breeder...      1
1       7.680980e+17  RT @MianUsmanJaved: Congratulations Pakistan o...      1
2       7.680980e+17  RT @PEPalerts: This September, @YESmag is taki...      1
3       7.680980e+17  RT @david_gaibis: Newly painted walls, thanks ...      1
4       7.680980e+17  RT @CedricFeschotte: Excited to announce: as o...      1
...              ...                                                ...    ...
550386  8.046170e+17  @goddesses_o I can't stop watching her...mm. M...      0
550387  8.046180e+17  Poor old Tom Odell doesn't look like he would ...      0
550388  8.046180e+17  #antsmasher I smashed  7 ants in this awesome ...      1
550389  8.046180e+17  @LizHudston @KymWyllie @Evasmiless @meanBok @l...      1
550390  8.046190e+17  Bixbeat Mixtape Vol.2 is here with great artis...      1

[550391 rows x 3 columns]

In [131]:
US_Elections_df['text'] = US_Elections_text.apply(remove_html)
US_Elections_df

,text,sentiment,negative_reason
0,"b'@robreiner so afraid of Nov, Dec, and Jan! E...",0,covid19
1,"b""RT @SueC00K: Lord Sumption launches Recovery...",0,others
2,b'RT @WalidPhares: Uber Timing: after #Biden a...,0,covid19
3,b'Every 107 seconds an American is dying from ...,1,NaN
4,b'RT @thewebbix: The #Democrats embrace #Diver...,1,NaN
...,...,...,...
2547,"b'RT @BoycottUtah: It is Friday, October 30, 2...",1,NaN
2548,b'@nowthisnews Delivered today in Montgomery C...,1,NaN
2549,b'@DonaldJTrumpJr DUHnnie Jr. lied on Fox when...,0,covid19
2550,b'RT @Pale_Ranger: Any ideas why @JoeBiden is ...,0,covid19
2551,"b'RT @cazaresforcoc: game time, keep up our mo...",1,NaN

### 1.2 Html character codes (i.e., &...;) are replaced with an ASCII equivalent

In [132]:
# Normal form form for the Unicode string
# NFKD will apply the compatibility decomposition, i.e. replace all compatibility characters with their equivalents
# Encode create creates a byte string, which cannot be mixed with a regular string
# Decode can convert back to string again
def ASCII_equivalent(text):
    ASCII_text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    return ASCII_text

In [133]:
sentiment_analysis_df['text'] = sentiment_text.apply(ASCII_equivalent)
sentiment_analysis_df

                  ID                                               text  label
0       7.680980e+17  Josh Jenkins is looking forward to TAB Breeder...      1
1       7.680980e+17  RT @MianUsmanJaved: Congratulations Pakistan o...      1
2       7.680980e+17  RT @PEPalerts: This September, @YESmag is taki...      1
3       7.680980e+17  RT @david_gaibis: Newly painted walls, thanks ...      1
4       7.680980e+17  RT @CedricFeschotte: Excited to announce: as o...      1
...              ...                                                ...    ...
550386  8.046170e+17  @goddesses_o I can't stop watching her...mm. M...      0
550387  8.046180e+17  Poor old Tom Odell doesn't look like he would ...      0
550388  8.046180e+17  #antsmasher I smashed  7 ants in this awesome ...      1
550389  8.046180e+17  @LizHudston @KymWyllie @Evasmiless @meanBok @l...      1
550390  8.046190e+17  Bixbeat Mixtape Vol.2 is here with great artis...      1

[550391 rows x 3 columns]

In [134]:
US_Elections_df['text'] = US_Elections_text.apply(ASCII_equivalent)
US_Elections_df

,text,sentiment,negative_reason
0,"b'@robreiner so afraid of Nov, Dec, and Jan! E...",0,covid19
1,"b""RT @SueC00K: Lord Sumption launches Recovery...",0,others
2,b'RT @WalidPhares: Uber Timing: after #Biden a...,0,covid19
3,b'Every 107 seconds an American is dying from ...,1,NaN
4,b'RT @thewebbix: The #Democrats embrace #Diver...,1,NaN
...,...,...,...
2547,"b'RT @BoycottUtah: It is Friday, October 30, 2...",1,NaN
2548,b'@nowthisnews Delivered today in Montgomery C...,1,NaN
2549,b'@DonaldJTrumpJr DUHnnie Jr. lied on Fox when...,0,covid19
2550,b'RT @Pale_Ranger: Any ideas why @JoeBiden is ...,0,covid19
2551,"b'RT @cazaresforcoc: game time, keep up our mo...",1,NaN

### 1.3 Remove all URLs

In [135]:
def remove_URL(text):
    cleanr = re.compile(r'\w+:\/{2}[\d\w-]+(\.[\d\w-]+)*(?:(?:\/[^\s/]*))*')
    cleantext = re.sub(cleanr, '', text)
    return cleantext

In [136]:
sentiment_analysis_df['text'] = sentiment_text.apply(remove_URL)
sentiment_analysis_df

                  ID                                               text  label
0       7.680980e+17  Josh Jenkins is looking forward to TAB Breeder...      1
1       7.680980e+17  RT @MianUsmanJaved: Congratulations Pakistan o...      1
2       7.680980e+17  RT @PEPalerts: This September, @YESmag is taki...      1
3       7.680980e+17  RT @david_gaibis: Newly painted walls, thanks ...      1
4       7.680980e+17  RT @CedricFeschotte: Excited to announce: as o...      1
...              ...                                                ...    ...
550386  8.046170e+17  @goddesses_o I can't stop watching her...mm. M...      0
550387  8.046180e+17  Poor old Tom Odell doesn't look like he would ...      0
550388  8.046180e+17  #antsmasher I smashed  7 ants in this awesome ...      1
550389  8.046180e+17  @LizHudston @KymWyllie @Evasmiless @meanBok @l...      1
550390  8.046190e+17  Bixbeat Mixtape Vol.2 is here with great artis...      1

[550391 rows x 3 columns]

In [137]:
US_Elections_df['text'] = US_Elections_text.apply(remove_URL)
US_Elections_df

,text,sentiment,negative_reason
0,"b'@robreiner so afraid of Nov, Dec, and Jan! E...",0,covid19
1,"b""RT @SueC00K: Lord Sumption launches Recovery...",0,others
2,b'RT @WalidPhares: Uber Timing: after #Biden a...,0,covid19
3,b'Every 107 seconds an American is dying from ...,1,NaN
4,b'RT @thewebbix: The #Democrats embrace #Diver...,1,NaN
...,...,...,...
2547,"b'RT @BoycottUtah: It is Friday, October 30, 2...",1,NaN
2548,b'@nowthisnews Delivered today in Montgomery C...,1,NaN
2549,b'@DonaldJTrumpJr DUHnnie Jr. lied on Fox when...,0,covid19
2550,b'RT @Pale_Ranger: Any ideas why @JoeBiden is ...,0,covid19
2551,"b'RT @cazaresforcoc: game time, keep up our mo...",1,NaN

### 1.4 All characters in the text are in lowercase.

In [138]:
sentiment_analysis_df['text'] = sentiment_text.str.lower()
sentiment_analysis_df

                  ID                                               text  label
0       7.680980e+17  josh jenkins is looking forward to tab breeder...      1
1       7.680980e+17  rt @mianusmanjaved: congratulations pakistan o...      1
2       7.680980e+17  rt @pepalerts: this september, @yesmag is taki...      1
3       7.680980e+17  rt @david_gaibis: newly painted walls, thanks ...      1
4       7.680980e+17  rt @cedricfeschotte: excited to announce: as o...      1
...              ...                                                ...    ...
550386  8.046170e+17  @goddesses_o i can't stop watching her...mm. m...      0
550387  8.046180e+17  poor old tom odell doesn't look like he would ...      0
550388  8.046180e+17  #antsmasher i smashed  7 ants in this awesome ...      1
550389  8.046180e+17  @lizhudston @kymwyllie @evasmiless @meanbok @l...      1
550390  8.046190e+17  bixbeat mixtape vol.2 is here with great artis...      1

[550391 rows x 3 columns]

In [139]:
US_Elections_df['text'] = US_Elections_text.str.lower()
US_Elections_df

,text,sentiment,negative_reason
0,"b'@robreiner so afraid of nov, dec, and jan! e...",0,covid19
1,"b""rt @suec00k: lord sumption launches recovery...",0,others
2,b'rt @walidphares: uber timing: after #biden a...,0,covid19
3,b'every 107 seconds an american is dying from ...,1,NaN
4,b'rt @thewebbix: the #democrats embrace #diver...,1,NaN
...,...,...,...
2547,"b'rt @boycottutah: it is friday, october 30, 2...",1,NaN
2548,b'@nowthisnews delivered today in montgomery c...,1,NaN
2549,b'@donaldjtrumpjr duhnnie jr. lied on fox when...,0,covid19
2550,b'rt @pale_ranger: any ideas why @joebiden is ...,0,covid19
2551,"b'rt @cazaresforcoc: game time, keep up our mo...",1,NaN